version: '3'
services: 
  db:
    image: 'mysql:5.7'
    volumes:
      - 'db_data:/var/lib/mysql'
    environment: 
      MYSQL_ROOT_PASSWORD: supw
      MYSQL_DATABASE: moodle
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpw
    restart: 'always'
    networks: 
     - moodle

  moodle:
    build: .
    depends_on:
      - db
    ports: 
      - 80:80
    restart: always
    networks: 
      - moodle

volumes: 
  db_data: {}

networks: 
  moodle: